baseURL = "https://gracie-z.github.io/"
languageCode = "en-us"
title = "Yanxin Zhou"
theme = "barks"
publishDir = "docs"

[params.head]
  description = "third-year PhD student in Stats @Stanford"


[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope fa"
        url = "mailto:yanxin01@stanford.edu"
        weight = 1
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square ai"
        url = "https://scholar.google.com/citations?user=wxIV1rYAAAAJ&hl=en"
        weight = 2
    [params.social.arxiv]
        name = "arXiv"
        class = "ai ai-arxiv ai"
        url = "https://arxiv.org/a/zhou_y_20"
        weight = 3
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/Gracie-z"
        weight = 4
    [params.social.linkedin]
        name = "LinkedIn"
        class = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/yanxin-zhou-97a5952b8/"
        weight = 5



[params.colors]
    background_color = "#dce5dc"
    text_color = "#333333"
    link_color = "#6a9e6b"

[params.typography]
    title_font = "Gelasio"
    body_font = "Bona Nova"

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3

  [[menu.main]]
  name = "Talks"
  url = "/talks/"
  weight = 4

  [[menu.main]]
  name = "Beyond Math"
  url = "/beyond_math/"
  weight = 5

